#+BEGIN_COMMENT
.. title: 程序化广告术语概述
.. slug: cheng-xu-hua-yan-gao-zhu-yu-gai-shu
.. date: 2020-03-17 11:23:05 UTC+08:00
.. tags: draft
.. category: 广告 advertising
.. link: 
.. description: 
.. type: text
#+END_COMMENT

* 传统互联网广告术语

*** DSP (Demand-Side Platform)
DSP为需求方（即广告主或代理商）提供实时竞价投放平台。广告需求方可以在平台上管理广告活动及其投放策略，包括设置目标受众的定向条件、预算、出价、创意等。
*** Trading Desk
Trading Desk（采购交易平台），简称TD。

类似DSP，但需求方可以在TD上统一管理多个DSP平台的投放，包括分配投放预算、制定和调整投放策略，查看数据报告。

*** Ad Network
Ad Network(广告网盟)，简称ADN。

ADN可以被理解为媒体代理公司，通过为广告主采购媒体方流量，赚取中间差价，其代表有百度网盟等。
*** SSP(Supply-Side Platform（供应方平台），简称SSP)

SSP服务于媒体方，可以作为分散的流量入口、大小媒体的聚合平台。

*** Ad Exchange(Ad Exchange（广告交易平台），简称ADX。)
ADX提供的功能是交换，实现实时竞价、广告库存和广告需求的匹配。广告需求方可以随时改变自己的出价策略和所选择的资源。
*** PCP(Programmatic Creative Platform（程序化创意平台），简称PCP)
PCP专注于广告创意的投放优化，通过技术自动生成海量创意，并利用算法和数据对不同受众动态地展示广告并进行创意优化。
*** AVP(Data Management Platform（数据管理平台），简称DMP)
DMP能够为广告投放提供人群标签进行受众精准定向，并通过投放数据建立用户画像，进行人群标签的管理以及再投放。
*** MAP(Measurement&Analytics Platform（监测分析平台），简称MAP。)
MAP被广告主用于同步监测广告投放数据，评估广告投放平台数据的真实性，比如曝光量、点击量、受众属性等。

* 程序化互联万广告术语

*** Demographics 
人口统计特征，典型的人口统计特征包括年龄、性别、地区、学历、职业和收入等。

*** Cookie
电脑中记录用户在网络中的行为的文件；网站可通过Cookie来识别用户是否曾经访问过该网站。

*** Frequency
接触频次，在一个阶段或者时间内广告传输给同一个浏览器的次数；站点需要使用Cookie来管理广告频次；广告主可以通过限定这个次数来达到提高广告效果的目的。

*** Targeting
定向，通过内容匹配、用户构成或者过滤传递最适宜的广告给用户。例如：地域定向、操作系统定向、媒体定向、点位定向、浏览器定向、时段定向等等。

*** Target Audience
目标受众，简称TA, 即广告投放的目标对象。

*** Retargeting
重定向。即找出曾经对广告主的产品或服务产生兴趣的人，重新向他们投放该广告主的广告，被公认为精准程度最高、效果最突出的定向方式。

*** 频控
频次控制，即限制某个用户在某一时间段内看到该广告的次数，有效控制信息流失率。一般来说，用户看到同一广告创意的次数上升，点击率随之下降，所以根据频次控制用户触及广告创意便十分重要。

*** Cookie Mapping
因不同网站域名下Cookie无法跨域名调用，每个域名只能存储使用本域名下的Cookie，所以需要一个“Cookie Mapping”的环节，对不同域名下的Cookie进行匹配，便于跨域名识别用户。


*** Lookalike
目标用户扩量的方法，在目标用户定向时，根据种子用户的网络行为聚类分析类似的行为相似的网络行为的用户进行扩量。

*** API
Application Programming Interface（应用程序编程接口/应用程序界面），简称API。

是偏技术，技术接口的代名词。程序化广告很多时候需要通过技术接口的方式交换数据，是一些预先定义的程序代码。



* 程序化广告-交易模式术语

** RTB
Real Time Bidding(实时竞价)，也叫Open Auction（公开竞价），简称RTB。

流量需求方在广告交易平台中，设定广告流量底价的情况下，当有流量过来时，与其他程序化广告买家一起对流量出价，广告交易平台收到各个程序化买家的出价后，进行比价，价高者获得流量并同步竞价成功的结果。整个过程都是通过程序化的方式在 100 毫秒内完成的。


** PDB

Private Direct Buy（程序化直接购买）,简称RTB.

是目前国内市场最为常见和主流应用的一种私有交易模式。指流量需求方用确定的价格买断固定、优质的媒体资源，然后进行程序化广告的精准定向投放。常说的“保价保量”。


** PD

Preferred Deals（优先交易），简称PD.

与 PDB 区别在于，这种私有交易方式在广告资源上具有一定的不确定性。即流量需求方可以购买某一优质广告位，但其能获得多少曝光展示量却不能预先保证。常说的“保价不保量”。

** PA

Private Auction（私有竞价）,简称PA。

供应方平台将较优质的固定广告位资源专门拿出来，放在一个半公开市场中，仅由进入白名单的买方（VIP）进行竞价，价高者得。因此，广告位可以锁定，但采买价格和是否最终获得曝光都不能预先保证。常说的“不保价不保量”。


* 程序化广告-结算方式术语
** CPM

Cost Per Mille（每千次展示成本），简称CPM。

是曝光付费广告，即广告每被展现（曝光）一千次，广告主所应付的费用。

** CPC

Cost Per Click（每次点击成本），简称CPC。

是点击付费广告，即根据广告被点击的次数进行收费。

** CPA

Cost Per Action（每次行动成本），简称CPA。

是按用户行为作为指标来计费的广告。行为可以是注册、下载、安装、加入购物车、下单、咨询等。可细分如下：

CPD（Cost Per Download 每下载成本：按 APP 下载量计费）
CPI（Cost Per Install 每安装成本：按 APP 安装量计费）
CPS（Cost Per Sale 每销售成本：按实际销售产品量计费）
CPL（Cost Per Lead 每潜在客户获取成本：按搜集到潜在客户名单/销售线索数计费）等。

** oCPX

oCPX是以目标转化为优化方式的出价方式。其中o为Optimized （优化），包括 oCPC（优化点击出价）、oCPM（优化千次展现出价）、oCPA（优化行为出价）等。

oCPX 的本质还是广告主按照 CPC、CPM、CPA 付费，只是投放系统会采用更精准的点击率和转化率预估机制及算法等，将广告展现给最容易产生转化效果的用户，以获取到更精准流量的同时，提升广告效果，并降低转化成本。
* 程序化广告-效果术语
广告传播影响受众的认知、心理、行为和态度，由此带来的直接和间接广告效益，对广告效果的评估的也有着多方面要素和维度。


** ROI

Return On Investment（投资回报率），简称ROI。即营销者通过广告投放得到的经济回报占广告投入（花费）的比例。



** 曝光量

Impression，即曝光量，也被称为“展示量”、“展现量”。即投放期广告被展示的总次数。一般用户每浏览一次页面，同时页面中广告位的广告被展示一次，就是一个曝光。



** 点击量

Click，即点击量，为投放期用户点击某个广告的总次数。



** 点击率

Click-Through-Rate，即点击率，为广告被点击的次数与广告曝光次数的比例（Click/Impression*100%）。反映了广告的受关注程度，或用来衡量广告的吸引程度。


** 到达率

Reach Rate，即到达率，为到达量与点击量的比例（到达量/点击量*100%）。

到达量：即有多少用户点击广告后进入落地页。



** 转化率

Conversion Rate，即转化率，为转化量与点击量的比例（转化量/点击量*100%）。

转化量：即有多少用户点击广告并进入落地页（活动页）后，继续发生咨询、注册、下载、加入购物车、下单等行为。



** 留存率

特定周期内（如次日留存、七日留存等），留存用户数量（有多少用户留下来）占广告（当时）导入的新增用户数量的比例。留存率=留存用户数/新增用户数量*100%。

** LT&ARPU&LTV

和游戏行业相关的三个效果术语：

Life Time（生命周期）,简称LT：一个用户从第1次到最后1次参与游戏之间的时间段，一般按月计算平均值；
Average Revenue Per User（每用户平均收入），简称ARPU：活跃用户对游戏产生的平均收入。即ARPU = 总收入/总活跃用户；
Life Time Value（用户终生价值），简称LTV：用户在生命周期内为该游戏创造的收入总计，可以看成是一个ARPU 值的长期累计。即LTV = ARPUxLT。
